version: '3'
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
   sacod_reporteguias:
    image: 'tonyhernandezdelcid/sacod_reporteguias:latest'
    expose:
      - '8080'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - type: volume
        source: sacod_reporteguias
        target: /var/lib/sacod_reporteguias
    extra_hosts:
      - 'serverdb:192.168.11.6'
    networks:
      mynetwork:
        ipv4_address: 172.20.0.8
volumes:
  sacod_reporteguias:
      